[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "shanghai"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@avalabs/subnet-evm-contracts/=lib/icm-contracts/lib/subnet-evm/contracts/",
    "@teleporter/=lib/icm-contracts/contracts/teleporter/",
    "@teleporter-mocks/=lib/icm-contracts/contracts/mocks/",
    "@avalanche-interchain-token-transfer/=lib/icm-contracts/contracts/ictt/"
]

[rpc_endpoints]
local-c = "http://localhost:9650/ext/bc/C/rpc"
myblockchain = "http://localhost:9650/ext/bc/myblockchain/rpc"
fuji-c = "https://api.avax-test.network/ext/bc/C/rpc"
dispatch = "https://subnets.avax.network/dispatch/testnet/rpc"
mysubnet = "http://localhost:9650/ext/bc/mysubnet/rpc"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
